### ISSUE TITLE
Rake Preview runs on random port

### ISSUE THREAD

**Issue by WheresAlice** [WheresAlice/staticli#2]
We're currently using `task.HostConf.PublishAllPorts = true` which exposes all ports from the Dockerfile.  However it uses random port numbers on the host to do this.

It looks like we can use `task.HostConf.PortBindings` instead, but it's unclear how to actually use this.

**Comment by lucymhdavies** [comment]
Solution:

```
    task.HostConf.PortBindings = nat.PortMap{
        nat.Port("4000/tcp"): []nat.PortBinding{
            {HostIP: "0.0.0.0", HostPort: "1337"},
        },
    }
```

plus add the following to your imports:

```
import "github.com/docker/go-connections/nat"
```


Up to you whether you stick this in the `init()`, or put it in `SetInitFunc`

Personally, I'd do `SetInitFunc`, so that the user can specify a port.


Now this is of course quite awkward, and thus not in the spirit of Cali, so I should probably add a helper function to cali/docker.go for this.

**Comment by lucymhdavies** [comment]
You're quite possibly going to come up against docker dependency issues on this one in your dev laptop, as there's an embedded vendoring in docker/docker (moby/moby)

In my case, the following resolves that:

```
rm -rf $GOPATH/src/github.com/docker/docker/vendor/github.com/docker/go-connections
```

This isn't actually a problem when you run make, as at that point you're downloading the dependencies you need, rather than using whatever mess of nested vendors end up on your laptop thanks to docker/docker.
